version: "3"

services:
  code-editor:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "realtime-code-editor"
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules